### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by u-train** [sircfenner/StudioComponents#32]
It's been a lot of new features since the last release. When/how will the next one be carved out? (Todo-list of some kind maybe beyond the readme/docs?)

**Comment by sircfenner** [comment]
I'd like to at least:
- get the remaining components set up with hooks and clear out the remaining class-component baggage
- fix any outstanding bugs (e.g. Widget story) 
- address a few of the points in #23 

Not sure about committing to a definite list because I'm still going over some component ideas that I might want to get done first.

**Comment by u-train** [comment]
Makes sense! Having a list would be good, just note that it isn't finalized.

**Comment by sircfenner** [comment]
Actually, going to issue releases a lot more often because I want to test out some of the new components/logic in real plugins.

**Comment by u-train** [comment]
It might be worth adding a changelog then following [this convention](https://keepachangelog.com/en/1.0.0/).
